### PR TITLE
solve some minor mistakes in the blog

### PR DESCRIPTION
**Pull request by Yuaninga**
Signed-off-by: Yuaninga <1846225041@qq.com>

### CODE REVIEW

**Comment by Yuaninga** [comment]
pass

**Comment by sunny0826** [comment]
@Yuaninga @caofujiang Just a question, what do `code pass` and `pass` mean?

**Comment by sunny0826** [comment]
> > @Yuaninga @caofujiang Just a question, what do `code pass` and `pass` mean?
> > I mistakenly think that comments are necessary. Sorry for your confusion.

Don't worry. You can write more to express your ideas. 

**Thank you for your contribution and I look forward to more from you.**

**Review by sunny0826 — APPROVED** [review]
LGTM

**Pull request merged**
