### PR TITLE
solve the problem of blog pictures

### PR DESCRIPTION
**Pull request by Yuaninga**
Signed-off-by: Yuaninga <1846225041@qq.com>

### CODE REVIEW

**Review by sunny0826 — APPROVED** [review]
thx for your contribution
LGTM

**Comment by sunny0826** [comment]
Hi @Yuaninga , your commit shows `Merge without waiting for requirements to be met (bypass branch protections)` every time, please follow the requirements in the link to fix your commit.
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
image

**Comment by sunny0826** [comment]
@Yuaninga 
**tips:** After fork, please checkout a new branch to make changes and commit PR based on the new branch, master is **only used to** synchronize the changes in origin. 
refer: https://guoxudong.io/post/contribution-to-the-open-source/#heading3

**Review by caofujiang — COMMENTED** [review]
LGTM

**Comment by Yuaninga** [comment]
> @Yuaninga **tips:** After fork, please checkout a new branch to make changes and commit PR based on the new branch, master is **only used to** synchronize the changes in origin. refer: https://guoxudong.io/post/contribution-to-the-open-source/#heading3

Roger that, thank you.

**Pull request closed without merging**
